Improve VPN commands execution logic
- Add logic to toggle connection if selection is current_conf
- Make sure that, if selection isn't the active conf, selection is in
  conf_files
- Exit with error if no condition is met

diff --git a/rofi-mullvad b/rofi-mullvad
--- a/rofi-mullvad
+++ b/rofi-mullvad
@@ -48,8 +48,13 @@ fi
 
 # Execute VPN commands
 if [[ -z "$current_conf" ]]; then
-  as_root wg-up $selection
-else
+  as_root wg-up "$selection"
+elif [[ "$current_conf" = "$selection" ]]; then
+  as_root wg-down "$current_conf"
+elif grep -q "$selection" <<< "$conf_files"; then
   as_root wg-down "$current_conf"
   as_root wg-up "$selection"
+else
+  echo "Error: Invalid WireGuard file name"
+  exit 1
 fi
